name: pyhakettu
favicon: null
layout_spectrum: 0.538197826128453
typography_spectrum: 0.6499475894961506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3732391179073602
  lightness: 0.21265768818557262
  saturation: 0.7932881829328835
  rhythmicContrast: 0.5537360631860793
purpose: []
