name: pyhakettu
favicon: null
layout_spectrum: 0.538197826128453
typography_spectrum: 0.13117
title: Saint Fox
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fdc79d'
    - '#5f5148'
    - '#d38b5c'
    - '#110b0a'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
